image: python:3.10

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install ./shared
  - pip install -r requirements.txt

test_calendar_service:
  stage: test
  script:
    - mv $CI_PROJECT_DIR/shared calendar_service/
    - cd calendar_service
    - python3 -m pytest
    - mv shared/ $CI_PROJECT_DIR

test_user_service:
  stage: test
  script:
    - mv $CI_PROJECT_DIR/shared user_service/
    - cd user_service
    - python3 -m pytest
    - mv shared/ $CI_PROJECT_DIR

test_event_service:
  stage: test
  script:
    - mv $CI_PROJECT_DIR/shared event_service/
    - cd event_service
    - python3 -m pytest
    - mv shared/ $CI_PROJECT_DIR
